import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 侧边栏：自动扫描 docs 目录生成
 * - 目录顺序由文件夹前缀（01-, 02-...）决定
 * - 每个目录的 label 从 _category_.json 读取
 * - 每篇文章的顺序由 frontmatter 里的 sidebar_position 决定
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
